### PR TITLE
Adding Step Functions component module

### PR DESCRIPTION
**Pull request by jacksandom**

### CODE REVIEW

**Comment by jacksandom** [comment]
Hi AJ,

Failing a check - airflow-on-aws - not sure what this is?

Jack

**Comment by aaronsteers** [comment]
> Failing a check - airflow-on-aws - not sure what this is?

Thanks @jacksandom - Looks like an issue on my side related to an update over the weekend. Very sorry about that. I'll look into this today and post back.

**Comment by aaronsteers** [comment]
@jacksandom - I just applied some fixes to the master branch and then merged those into this branch. Tests are passing again! 🎉

**Comment by aaronsteers** [comment]
@jacksandom - I had some more time to review and this looks like this is on the right track - very exciting! 

No major concerns here as of yet, but can you go ahead and add a new `ml-ops` sample using the lambda sample as a starting point:
- https://github.com/slalom-ggp/dataops-infra/tree/master/samples/s3-lambda-trigger

And please also register the sample here in this list so it can get CI/CD testing:
- https://github.com/slalom-ggp/dataops-infra/blob/master/.github/workflows/terraform-ci-cd.yml#L38

**Comment by aaronsteers** [comment]
@jacksandom - I just noticed you've closed and merged the PR - sorry, I was not very clear but I was hoping we could keep this open until we finalize the testing and implementation details. Do you mind opening up a new one for the samples mentioned above and any other follow-on work? Thanks!

**Pull request merged**
